=== grizzie17/WebDBtemplate/App_Data/announcements_calendar/remind.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!-- edited with XMLSpy v2008 rel. 2 sp2 (http://www.altova.com) by grizzie (Bear Consulting Group) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<!--Please add namespace attributes, a targetNamespace attribute and import elements according to your requirements-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="reminders">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="event" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="include" minOccurs="0"/>
			</xs:choice>
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="href" type="xs:anyURI"/>
			<xs:attribute name="cache-file" type="xs:anyURI" use="optional" />
			<xs:attribute name="cache-interval" type="xs:string" use="optional" />
			<xs:attribute name="cache-value" type="xs:integer" use="optional" />
			<xs:attribute name="cache-break-interval" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="date" maxOccurs="unbounded"/>
				<xs:element ref="category" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="style" minOccurs="0"/>
				<xs:element ref="subject"/>
				<xs:element ref="location" minOccurs="0"/>
				<xs:element ref="content" minOccurs="0"/>
				<xs:element ref="comments" minOccurs="0"/>
				<xs:element ref="author" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:anySimpleType"/>
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="date">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="single"/>
						<xs:enumeration value="season"/>
						<xs:enumeration value="moon"/>
						<xs:enumeration value="weekly"/>
						<xs:enumeration value="keyword"/>
						<xs:enumeration value="yearly"/>
						<xs:enumeration value="hebrew"/>
						<xs:enumeration value="monthly"/>
						<xs:enumeration value="julian"/>
						<xs:enumeration value="daily"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="weekly" />
			<xs:attribute name="monthly" type="DayType"/>
			<xs:attribute name="yearly" type="DayType"/>
			<xs:attribute name="hebrew" type="DayType"/>
			<xs:attribute name="offset" type="xs:anySimpleType"/>
			<xs:attribute name="duration" type="xs:anySimpleType"/>
			<xs:attribute name="duration-view" type="xs:anySimpleType"/>
			<xs:attribute name="pending" type="xs:anySimpleType"/>
			<xs:attribute name="time" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="category">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="style">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="subject">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="location">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="content">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="comments">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:complexType mixed="true">
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="DayType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="dayn"/>
			<xs:enumeration value="wday"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== grizzie17/WebDBtemplate/App_Data/remind/Motorcycle_Alabama;categories.xml
<?xml version="1.0"?>
<reminders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="remind.xsd">
	<event id="e20040119215731"><date type="yearly" yearly="wday" offset="# -2" duration="3" duration-view="mag" pending="5">06 2 1</date><category>motorcycle</category><category>rally</category><category>email2</category><category>external</category><style>RmdMotorcycle</style><subject><![CDATA[http://www.lynchburgmotorcyclerally.com/ [Lynchburg Motorcycle Rally]]]></subject></event><event id="e20040120142334"><date type="yearly" yearly="wday" pending="5">09 2 1</date><category>motorcycle</category><category>charity</category><category>rally</category><category>ride</category><category>email</category><category>external</category><style>RmdMotorcycle</style><subject><![CDATA[http://www.ride4kids.org/ [Ride for Kids]]]></subject><content><![CDATA[Birmingham, AL]]></content></event><event id="e20050906220724"><date type="yearly" yearly="wday">06 1 7</date><category>charity</category><category>external</category><category>email2</category><style>RmdMotorcycleLocal</style><subject><![CDATA[http://www.goodsamaritanride.com/ [Good Samaritan Ride]]]></subject></event><event id="e20060417233939"><date type="yearly" yearly="wday" pending="5">06 2 7</date><category>external</category><category>charity</category><category>email</category><category>motorcycle</category><style>RmdMotorcycle</style><subject><![CDATA[http://www.campsam.org/ [Camp Smile-A-Mile] Motorcycle Ride]]></subject><content><![CDATA[Birmingham]]></content></event><event id="e20080329094011"><date type="yearly" yearly="wday">04 3 7</date><category>charity</category><category>email</category><category>external</category><style>RmdCharityInfo</style><subject><![CDATA[http://www.RiverCityThunderRally.com/ [River City Thunder Rally]]]></subject><content><![CDATA[Benefit for Morgan County Child Advocacy Center]]></content></event></reminders>

=== grizzie17/WebDBtemplate/App_Data/remind/Chapter_eventz2;motorcycle;categories;sort=aab.xml
<?xml version="1.0"?>
<reminders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="remind.xsd">
	<event id="e20051206215638"><date type="yearly" yearly="wday" time="18:30">12 2 7</date><category>al-x</category><category>x-gathering</category><category>meeting</category><category>supper</category><category>party</category><category>email</category><category>x-meeting</category><category>funday</category><style>RmdGathering</style><subject><![CDATA[Your Chapter Christmas Party]]></subject><content><![CDATA[address:108-C+1st+Street+South,+Alabaster,+AL [Restaurant Name], Brief Directions, 6:30pm. Don't forget your Dirty Santa gift ]]></content></event><event id="e20050521233813"><date type="yearly" yearly="dayn">01 04</date><category>birthday</category><category>email2</category><category>newsletter</category><style>birthday</style><subject><![CDATA[Your Chapter]]></subject><content><![CDATA[Charter {{year 1983}} Anniversary]]></content></event><event id="e20081212163322"><date type="monthly" monthly="wday" time="18:30" offset="? m12 ++ cancel">1 1 2 4</date><category>al-x</category><category>x-gathering</category><category>x-meeting</category><category>meeting</category><category>email</category><category>supper</category><style>RmdGathering</style><subject><![CDATA[Your Chapter gathering]]></subject><content><![CDATA[address:108-C+1st+Street+South,+Alabaster,+AL [Restaurant Name], Brief Directions, Eat 6:30pm / Meet 7:30pm]]></content></event></reminders>

=== grizzie17/WebDBtemplate/App_Data/remind/External_events;motorcycle;categories.xml
<?xml version="1.0" encoding="utf-8"?>
<reminders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="remind.xsd">
	<event id="e20050528135631">
		<date type="yearly" yearly="wday" offset="# -2">06 3 1</date>
		<category>email2</category>
		<category>external</category>
		<style>RmdMotorcycle</style>
		<subject><![CDATA[http://www.hannigantrikes.com/ [Hannigan Homecoming]]]></subject><content><![CDATA[Hannigan Motorsports, 4044 U.S. Hwy. 641 South, Murray, Kentucky 42071]]></content>
	</event>
	<event id="e20050626195653">
		<date type="yearly" yearly="wday">10 4 7</date>
		<category>email2</category>
		<category>external</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.lynchburgtenn.com/jack_daniels_bar-b-q.html [Jack Daniel's Barbecue]]]></subject></event><event id="e20050629220110"><date type="yearly" yearly="wday">10 1 7</date><category>email2</category><category>external</category><category>entertainment</category><style>entertainment</style><subject><![CDATA[http://www.madisonstreetfestival.org/ [Madison Street Festival]]]></subject></event><event id="e20060111110126"><date type="yearly" yearly="wday" offset="# -3">04 1 1</date><category>external</category><category>email</category><category>entertainment</category><style>entertainment</style><subject><![CDATA[http://www.muleday.com/ [Mule Day]]]></subject><content><![CDATA[Columbia, TN]]></content>
	</event>
	<event id="e20060112210506">
		<date type="yearly" yearly="dayn" offset="++ 1 # -1">01 02</date>
		<category>external</category>
		<category>email</category>
		<style>RmdMotorcycle</style>
		<subject><![CDATA[http://www.appletonmotorcycle.com/ [Music City Motorcycle Bike Show]]]></subject></event><event id="e20060224161126"><date type="single">2009 02 20</date><category>external</category><category>email2</category><category>rally</category><style>RmdMotorcycle</style><subject><![CDATA[http://www.motorcycleshows.com/motorcycleshows/static/staticHtml.jsp?id=359197 [Cycle World/International Motorcycle Shows]]]></subject><content><![CDATA[Carolina First Center, Greenville, SC. Thru Sunday]]></content>
	</event>
	<event id="e20060226174930">
		<date type="yearly" yearly="wday">05 3 6</date>
		<category>external</category>
		<style>RmdCharityInfo</style>
		<subject><![CDATA[http://nascar.com/nascarday [NASCAR Day]]]></subject></event><event id="e20060419144136"><date type="yearly" yearly="wday" offset="# -1">06 1 7</date><category>external</category><category>rally</category><category>email2</category><style>RmdMotorcycle</style><subject><![CDATA[http://www.wakinthedragonbikerrally.com/ [Wakin' the Dragon Biker Rally]]]></subject><content><![CDATA[Punkin Center Motorcycle Resort, Maryville, Tennessee]]></content>
	</event>
	<event id="e20060717224614">
		<date type="yearly" yearly="wday">10 1 1</date>
		<category>external</category>
		<category>email</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.cullmanoktoberfest.com/ [Cullman Oktoberfest]]]></subject><content><![CDATA[One week]]></content>
	</event>
	<event id="e20060717230509">
		<date type="yearly" yearly="wday">04 4 7</date>
		<category>external</category>
		<category>email</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.bloominfestival.com/ [Bloomin' Festival]]]></subject><content><![CDATA[St. Bernard Preparatory School (Ave Maria Grotto)]]></content>
	</event>
	<event id="e20060717231354">
		<date type="yearly" yearly="wday" offset="# -1">04 4 1</date>
		<category>external</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.ardmore-renfaire.com/ [Ardmore Renaissance Festival]]]></subject></event><event id="e20060717231704"><date type="yearly" yearly="wday" offset="# -2">04 -1 1</date><category>external</category><category>entertainment</category><style>entertainment</style><subject><![CDATA[http://www.panoply.org/ [Panoply Arts Festival]]]></subject></event><event id="e20060717232440"><date type="yearly" yearly="wday">08 3 7</date><category>external</category><category>entertainment</category><style>entertainment</style><subject><![CDATA[http://www.franklincountychamber.org/festival.html [Watermelon Festival]]]></subject><content><![CDATA[Franklin County]]></content>
	</event>
	<event id="e20060717233722">
		<date type="yearly" yearly="wday">10 4 7</date>
		<category>external</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.alarenfaire.org/ [Alabama Renaissance Faire]]]></subject><content><![CDATA[Florence]]></content>
	</event>
	<event id="e20060724163516">
		<date type="yearly" yearly="wday" duration="4">08 1 5</date>
		<category>external</category>
		<category>email</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.127sale.com/ [World's Longest Yard Sale]]]></subject><location><![CDATA[Warning: Heavy Congestion]]></location>
		<content><![CDATA[Covington, KY to Gadsden, AL]]></content>
	</event>
	<event id="e20060818235354">
		<date type="yearly" yearly="wday" duration="2">10 3 7</date>
		<category>external</category>
		<category>email</category>
		<style>RmdMotorcycle</style>
		<subject><![CDATA[http://www.ahrma.org/ [American Historic Racing Motorcycle Association] Roadrace]]></subject>
		<content><![CDATA[Barber Motorsports Park, Birmingham]]></content>
	</event>
	<event id="e20060819224240">
		<date type="yearly" yearly="wday">10 4 7</date>
		<category>external</category>
		<category>entertainment</category>
		<category>email</category>
		<style>entertainment</style>
		<subject><![CDATA[http://800alabama.com/things-to-do/events/details.cfm?id=6700 [Covered Bridge Festival]]]></subject></event><event id="e20060920100655"><date type="single" duration="5">2008 10 06</date><category>email</category><category>external</category><category>newsletter</category><style>RmdInfo</style><subject><![CDATA[Madison County Area Schools Fall Break]]></subject>
	</event>
	<event id="e20061123103046">
		<date type="yearly" yearly="wday">05 3 7</date>
		<category>external</category>
		<category>email</category>
		<style>RmdMotorcycle</style>
		<subject><![CDATA[http://www.ahrma.org/ [American Historic Racing Motorcycle Association] Roadrace]]></subject>
		<content><![CDATA[Talladega Raceway]]></content>
	</event>
	<event id="e20061206223603">
		<date type="single">2008 04 19</date>
		<category>external</category>
		<category>motorcycle</category>
		<category>lunch</category>
		<category>rally</category>
		<category>email2</category>
		<style>RmdMotorcycle</style>
		<subject><![CDATA[http://www.bikershack411.net/ [Crawfish Boil and Bike Show]]]></subject><content><![CDATA[Centre, AL]]></content>
	</event>
	<event id="e20061206224215">
		<date type="yearly" yearly="wday" offset="# -2">05 3 1</date>
		<category>external</category>
		<category>rally</category>
		<style>RmdMotorcycleLocal</style>
		<subject><![CDATA[http://www.bikeorama.org/ [Bike-O-Rama]]]></subject></event><event id="e20070114001820"><date type="yearly" yearly="wday" offset="# -2">05 3 1</date><category>external</category><category>motorcycle</category><category>rally</category><category>email2</category><style>RmdMotorcycleLocal</style><subject><![CDATA[http://www.rivercityride.com/ [River City Ride, Bike Rally and Blues Festival]]]></subject></event><event id="e20070123145332"><date type="yearly" yearly="wday" offset="# +5">09 3 1</date><category>motorcycle</category><category>charity</category><category>email2</category><style>RmdCharityInfo</style><subject><![CDATA[http://www.stjudeswingsacrosstn.com/ [Wings Across Tennessee]]]></subject><content><![CDATA[St. Jude Childrens Research Hospital]]></content>
	</event>
	<event id="e20070225203529">
		<date type="yearly" yearly="wday" offset="# -1">05 1 7</date>
		<category>external</category>
		<category>email</category>
		<category>entertainment</category>
		<style>entertainment</style>
		<subject><![CDATA[http://www.pokesalatfestival.com/ [Poke Salat Festival]]]></subject><content><![CDATA[Historic Downtown Arab]]></content>
	</event>
	<event id="e20071120234759">
		<date type="yearly" yearly="wday" offset="# 2">11 4 5</date>
		<category>email</category>
		<category>newsletter</category>
		<category>external</category>
		<style>entertainmentBig</style>
		<subject><![CDATA[Iron Bowl]]></subject>
	</event>
	<event id="e20080118142620">
		<date type="single">2009 02 17</date>
		<category>external</category>
		<category>newsletter</category>
		<category>email</category>
		<style>entertainmentBig</style>
		<subject><![CDATA[Analog TV Obsolete]]></subject>
	</event>
	<event id="e20080729194531">
		<date type="yearly" yearly="wday" pending="30">08 1 5</date>
		<category>external</category>
		<category>email2</category>
		<category>charity</category>
		<style>RmdCharityEnc</style>
		<subject><![CDATA[Dairy Queen - http://www.miracletreatday.com/ [Miracle Treat Day]]]></subject><content><![CDATA[All proceeds for purchased Blizzards are donated to Children's Miracle Network Hospitals]]></content>
	</event>
</reminders>

=== grizzie17/WebDBtemplate/App_Data/remind/Chapter_events;motorcycle;categories;sort=aaa.xml
<?xml version="1.0" encoding="utf-8"?>
<reminders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="remind.xsd">
	<event id="e20081016142155">
		<date type="single">2008 12 31</date>
		<category>al-b</category>
		<category>ride</category>
		<category>b-ride</category>
		<category>email</category>
		<style>RmdRide</style>
		<subject><![CDATA[End of Year Ride]]></subject>
		<content><![CDATA[tbd]]></content>
	</event>
	<event id="e20081016142300">
		<date type="single">2009 01 01</date>
		<category>al-b</category>
		<category>ride</category>
		<category>b-ride</category>
		<category>email</category>
		<style>RmdRide</style>
		<subject><![CDATA[Start of Year Ride]]></subject>
		<content><![CDATA[tbd]]></content>
	</event>
	<event id="e20081211150220"><date type="weekly" duration-view="mag">1 2,6</date><category>al-x</category><style>RmdEvent</style><subject><![CDATA[Sample Weekly Event]]></subject></event><event id="e20081218100857">
		<date type="keyword">moon full</date>
		<style>RmdGWRRA_National</style>
		<subject><![CDATA[Full Moon]]></subject>
	</event>
	<event id="e20081218102236">
		<date type="keyword">moon new</date>
		<style>RmdGWRRA_National</style>
		<subject><![CDATA[New Moon]]></subject>
	</event>
	<event id="e20091022171549"><date type="single">2009 10 22</date><style>RmdCharity</style><subject><![CDATA[Another Message]]></subject><content><![CDATA[Some body text 2222222]]></content></event></reminders>

=== grizzie17/WebDBtemplate/App_Data/remind/Education_events;motorcycle;categories.xml
<?xml version="1.0"?>
<reminders 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="remind.xsd">
	<event id="e20080206230456"><date type="single">2008 09 13</date><category>safety</category><category>external</category><category>email2</category><style>RmdSafetyInfo</style><subject><![CDATA[http://www.montevallo.edu/atsc/motorcycle/ [Experienced Rider Course]]]></subject><content><![CDATA[address:358+Bolling+Road,+Meridianville,+AL+35759 [Madison County Executive Airport]]]></content></event><event id="e20080206231444"><date type="single">2008 11 22</date><category>safety</category><category>external</category><category>email2</category><style>RmdSafetyInfo</style><subject><![CDATA[http://www.montevallo.edu/atsc/motorcycle/ [Experienced Rider Course]]]></subject><content><![CDATA[address:358+Bolling+Road,+Meridianville,+AL+35759 [Madison County Executive Airport]]]></content></event><event id="e20080805164356"><date type="single">2008 10 04</date><category>safety</category><category>external</category><category>email2</category><style>RmdSafetyInfo</style><subject><![CDATA[http://www.montevallo.edu/atsc/motorcycle/ [Experienced Rider Course]]]></subject><content><![CDATA[address:358+Bolling+Road,+Meridianville,+AL+35759 [Madison County Executive Airport]]]></content></event></reminders>
